const cartRouter = require("./cart.route");
const productRouter = require("./products.route");
const userRouter = require("./user.route");
const cartProductRouter = require("./cart-products.route");
const { Router } = require("express");
const router = Router();
router.use("/cart", cartRouter);
router.use("/products", productRouter);
router.use("/user", userRouter);
router.use("/cart-products", cartProductRouter);
module.exports = router;
